name: animals_checker_get
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.1.0
  dio: ^5.4.1 
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  get: ^4.6.6
  flutter_svg: ^1.1.6
  cached_network_image: ^3.3.1
  auto_size_text: ^3.0.0
  responsive_builder: ^0.7.0
  go_router: ^13.2.4
  flutter_html: ^3.0.0-beta.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - lib/assets/
