// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnJ_PkNcZmc6NcyUX76YCaxnN6LtcTEmE',
    appId: '1:1013281379045:web:5d53b47f1647bda9fafa0c',
    messagingSenderId: '1013281379045',
    projectId: 'redlist-7bd64',
    authDomain: 'redlist-7bd64.firebaseapp.com',
    storageBucket: 'redlist-7bd64.appspot.com',
    measurementId: 'G-J84M0Z38V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSuvnhI6ToiKyS2Ges_ctDcDFicOHbfzs',
    appId: '1:1013281379045:android:b00634d5f691f82ffafa0c',
    messagingSenderId: '1013281379045',
    projectId: 'redlist-7bd64',
    storageBucket: 'redlist-7bd64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbqfdLinmogOP3aAI_DNAmW6vez70guq4',
    appId: '1:1013281379045:ios:02785159a44d49ddfafa0c',
    messagingSenderId: '1013281379045',
    projectId: 'redlist-7bd64',
    storageBucket: 'redlist-7bd64.appspot.com',
    iosBundleId: 'com.example.animalsCheckerGet',
  );
}
